language: minimal
os: linux
arch: amd64
dist: bionic
branches: 
  except:
    - CI-latest
script:
- git submodule update --init --recursive
- sudo apt install -y build-essential automake autoconf git squashfs-tools pkg-config curl
- sudo apt install -y libssl-dev libncurses5-dev bc m4 unzip python
- wget -O _fwup.deb https://github.com/fhunleth/fwup/releases/download/v1.7.0/fwup_1.7.0_amd64.deb
- sudo dpkg -i _fwup.deb
- git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.8
- echo -e "\n. $HOME/.asdf/asdf.sh" >> ~/.bashrc
- source ~/.bashrc
- asdf plugin-add erlang
- asdf plugin-add elixir
- travis_wait asdf install erlang 22.3.2
- asdf install elixir 1.10.2-otp-22
- asdf local erlang 22.3.2
- asdf local elixir 1.10.2-otp-22
- pwd
- mix --version
- mix local.hex --force
- mix local.rebar --force
- mix archive.install hex nerves_bootstrap --force
- cd farmbot_os
- MIX_TARGET=rpi4 mix deps.get --force
- MIX_TARGET=rpi4 mix firmware
- mkdir $TRAVIS_BUILD_DIR/_artifacts
- cp $TRAVIS_BUILD_DIR/farmbot_os/_build/rpi4/rpi4_dev/nerves/images/farmbot.fw $TRAVIS_BUILD_DIR/_artifacts/farmbot-rpi4-dev.fw
- fwup -a -t complete -i $TRAVIS_BUILD_DIR/_artifacts/farmbot-rpi4-dev.fw -d $TRAVIS_BUILD_DIR/_artifacts/farmbot-rpi4-dev.img
before_deploy:
- |
  if [[ -z "$TRAVIS_TAG" ]]; then
    export TRAVIS_TAG=CI-latest
  fi
deploy:
- provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file: 
  - $TRAVIS_BUILD_DIR/_artifacts/farmbot-rpi4-dev.img
  skip_cleanup: true
  prerelease: true
  draft: false
  overwrite: true
  on:
    tags: false
    branch: bluewaysw-rpi4